# Generated by Django 5.1.3 on 2025-05-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_payment_id_payment_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='metadata',
        ),
        migrations.AddField(
            model_name='payment',
            name='signature',
            field=models.CharField(default='', editable=False, max_length=64),
            preserve_default=False,
        ),
    ]
