# Generated by Django 5.1.3 on 2025-05-20 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_subscription_plan'),
        ('payments', '0004_remove_payment_metadata_payment_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='main.subscriptionplan', verbose_name='Тарифный план'),
            preserve_default=False,
        ),
    ]
