# Generated by Django 5.1.3 on 2024-12-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='close_time',
            field=models.TimeField(verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='open_time',
            field=models.TimeField(verbose_name='Время открытия'),
        ),
    ]
