# Generated by Django 5.1.3 on 2025-05-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_routes',
            field=models.PositiveIntegerField(default=0, verbose_name='Макс. маршрутов по подписке'),
        ),
    ]
