# Generated by Django 5.1.3 on 2024-12-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.ManyToManyField(to='routes.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='place',
            name='contacts',
            field=models.JSONField(blank=True, null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='place',
            name='full_description',
            field=models.TextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places_images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.JSONField(blank=True, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='place',
            name='reviews',
            field=models.TextField(blank=True, null=True, verbose_name='Отзывы(пока что пустое)'),
        ),
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=models.CharField(max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='place',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Изменено'),
        ),
    ]
