# Generated by Django 5.1.3 on 2024-12-12 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_workinghours_close_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together=set(),
        ),
    ]
