# Generated by Django 5.1.3 on 2025-05-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_customuser_max_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='max_routes',
            field=models.PositiveIntegerField(db_default=0, default=0, verbose_name='Макс. маршрутов по подписке'),
        ),
    ]
