# Generated by Django 5.1.3 on 2024-12-12 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_workinghours_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together={('place', 'day_of_week')},
        ),
    ]
