# Generated by Django 5.1.3 on 2024-12-12 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_workinghours_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together=set(),
        ),
    ]
