# Generated by Django 5.1.3 on 2025-05-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_customuser_max_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default='Санкт-Петербург', help_text='Город, в котором находится это место', max_length=100, verbose_name='Город'),
        ),
    ]
