# Generated by Django 5.1.3 on 2025-02-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_alter_workinghours_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name': 'День маршрута', 'verbose_name_plural': 'Дни маршрутов'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterModelOptions(
            name='routecell',
            options={'verbose_name': 'Ячейка маршрута', 'verbose_name_plural': 'Ячейки маршрутов'},
        ),
    ]
