# Generated by Django 5.1.3 on 2025-05-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subscription_amount_subscription_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='currency',
        ),
    ]
