# Generated by Django 5.1.3 on 2025-05-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subscriptionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='key',
            field=models.CharField(editable=False, help_text='Автоматически сгенерированный уникальный код плана', max_length=50, unique=True),
        ),
    ]
